import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";

const nunito = Nunito({
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Aldi Pratama | Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.className} antialiased font-bold min-h-screen min-w-screen overflow-hidden`}
      >
        {children}
      </body>
    </html>
  );
}
